-- Pawn to Professor Learning Hub v1.3
-- Secure Game Launcher - phase 1 migration
-- Run AFTER the base schema + v1.1 + v1.2 migrations.
-- Safe to run while v1.2 is still live: old launch_url values are copied but NOT removed yet.

create table if not exists public.activity_targets (
  activity_id uuid primary key references public.activities(id) on delete cascade,
  target_url text not null,
  security_mode text not null default 'unit'
    check (security_mode in ('public','members','unit')),
  launch_ttl_seconds integer not null default 180
    check (launch_ttl_seconds between 60 and 900),
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Copy existing game links into the protected target table.
insert into public.activity_targets (activity_id, target_url, security_mode, enabled)
select id, launch_url, 'unit', true
from public.activities
where launch_url is not null and btrim(launch_url) <> ''
on conflict (activity_id) do nothing;

-- New v1.3 activities no longer need a public launch_url value.
alter table public.activities
  alter column launch_url drop not null;

-- Launch tokens are server-only. The browser gets the raw token; only its hash is stored.
create table if not exists public.game_launch_tokens (
  id bigint generated by default as identity primary key,
  token_hash text unique not null,
  activity_id uuid not null references public.activities(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  last_validated_at timestamptz
);

create index if not exists game_launch_tokens_activity_idx
  on public.game_launch_tokens(activity_id);
create index if not exists game_launch_tokens_expiry_idx
  on public.game_launch_tokens(expires_at);

alter table public.activity_targets enable row level security;
alter table public.game_launch_tokens enable row level security;

-- Only staff can see or edit the real target URL from the browser.
drop policy if exists activity_targets_admin_all on public.activity_targets;
create policy activity_targets_admin_all
on public.activity_targets for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant select, insert, update, delete on public.activity_targets to authenticated;

-- No anon/authenticated RLS policies are created for game_launch_tokens.
-- They are intentionally accessible only through the Vercel server using the Supabase secret key.

-- Keep updated_at current.
drop trigger if exists activity_targets_set_updated_at on public.activity_targets;
create trigger activity_targets_set_updated_at
before update on public.activity_targets
for each row execute function public.set_updated_at();

-- Optional housekeeping helper. Server can call it through service-role RPC if desired.
create or replace function public.delete_expired_game_launch_tokens()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  delete from public.game_launch_tokens
  where expires_at < now() - interval '1 hour';
  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

-- IMPORTANT: Do not clear activities.launch_url yet.
-- Deploy/test v1.3 first, then run v1.3-finalize-hide-legacy-urls.sql.
