-- Pawn to Professor Learning Hub v1.6.8
-- Admin-only detailed usage analytics
-- Run AFTER v1.6.1. Safe to run more than once.

begin;

-- ---------------------------------------------------------------------------
-- 1) Usage event ledger
-- ---------------------------------------------------------------------------
create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  username text not null,
  display_name text,
  event_type text not null,
  school_year_id uuid references public.school_years(id) on delete set null,
  grade_id uuid references public.grades(id) on delete set null,
  unit_id uuid references public.units(id) on delete set null,
  activity_id uuid references public.activities(id) on delete set null,
  resource_id uuid references public.resources(id) on delete set null,
  tool_id uuid references public.external_tools(id) on delete set null,
  content_title text not null,
  path_text text,
  page_name text,
  created_at timestamptz not null default now(),
  constraint usage_events_type_check check (
    event_type in (
      'portal_home_view',
      'year_view',
      'grade_view',
      'unit_view',
      'game_play',
      'resource_view',
      'resource_download',
      'tools_view',
      'tool_open',
      'community_view',
      'community_category_view',
      'forum_topic_view'
    )
  )
);

create index if not exists idx_usage_events_created
  on public.usage_events(created_at desc);

create index if not exists idx_usage_events_user_created
  on public.usage_events(user_id, created_at desc);

create index if not exists idx_usage_events_type_created
  on public.usage_events(event_type, created_at desc);

create index if not exists idx_usage_events_activity_created
  on public.usage_events(activity_id, created_at desc)
  where activity_id is not null;

create index if not exists idx_usage_events_resource_created
  on public.usage_events(resource_id, created_at desc)
  where resource_id is not null;

create index if not exists idx_usage_events_tool_created
  on public.usage_events(tool_id, created_at desc)
  where tool_id is not null;

alter table public.usage_events enable row level security;

-- Normal members never read the analytics ledger.
revoke all on public.usage_events from anon, authenticated;
grant select on public.usage_events to authenticated;

drop policy if exists usage_events_admin_read on public.usage_events;
create policy usage_events_admin_read
on public.usage_events
for select
to authenticated
using (public.is_admin());

-- ---------------------------------------------------------------------------
-- 2) Secure logger
-- Browsers call this RPC. It derives names/paths on the server so members
-- cannot forge another username or fake the title of the content.
-- ---------------------------------------------------------------------------
create or replace function public.log_usage_event(
  p_event_type text,
  p_school_year_id uuid default null,
  p_grade_id uuid default null,
  p_unit_id uuid default null,
  p_activity_id uuid default null,
  p_resource_id uuid default null,
  p_tool_id uuid default null,
  p_page_name text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_username text;
  v_display_name text;
  v_year_id uuid := p_school_year_id;
  v_grade_id uuid := p_grade_id;
  v_unit_id uuid := p_unit_id;
  v_activity_id uuid := p_activity_id;
  v_resource_id uuid := p_resource_id;
  v_tool_id uuid := p_tool_id;
  v_title text;
  v_path text;
  v_page_name text := nullif(trim(coalesce(p_page_name, '')), '');
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if not public.account_is_active() then
    raise exception 'Account is not active';
  end if;

  if p_event_type not in (
    'portal_home_view',
    'year_view',
    'grade_view',
    'unit_view',
    'game_play',
    'resource_view',
    'resource_download',
    'tools_view',
    'tool_open',
    'community_view',
    'community_category_view',
    'forum_topic_view'
  ) then
    raise exception 'Unsupported analytics event';
  end if;

  select p.username::text, p.display_name
    into v_username, v_display_name
  from public.profiles p
  where p.id = v_user_id;

  if v_username is null then
    raise exception 'Profile not found';
  end if;

  -- Exact game name + Unit/Grade/Year path.
  if p_event_type = 'game_play' then
    select
      a.title,
      a.id,
      u.id,
      g.id,
      y.id,
      concat_ws(' / ', y.name, g.name, u.name)
    into
      v_title,
      v_activity_id,
      v_unit_id,
      v_grade_id,
      v_year_id,
      v_path
    from public.activities a
    join public.units u on u.id = a.unit_id
    join public.grades g on g.id = u.grade_id
    join public.school_years y on y.id = g.school_year_id
    where a.id = p_activity_id
      and (public.is_admin() or public.has_unit_access(a.unit_id));

    if v_title is null then
      raise exception 'Activity is not available';
    end if;

  -- Exact resource name + Unit/Grade/Year path.
  elsif p_event_type in ('resource_view', 'resource_download') then
    select
      r.title,
      r.id,
      u.id,
      g.id,
      y.id,
      concat_ws(' / ', y.name, g.name, u.name)
    into
      v_title,
      v_resource_id,
      v_unit_id,
      v_grade_id,
      v_year_id,
      v_path
    from public.resources r
    join public.units u on u.id = r.unit_id
    join public.grades g on g.id = u.grade_id
    join public.school_years y on y.id = g.school_year_id
    where r.id = p_resource_id
      and (
        public.is_admin()
        or (r.audience = 'unit' and public.has_unit_access(r.unit_id))
      );

    if v_title is null then
      raise exception 'Resource is not available';
    end if;

  -- Exact external tool name.
  elsif p_event_type = 'tool_open' then
    select t.name, t.id
      into v_title, v_tool_id
    from public.external_tools t
    where t.id = p_tool_id
      and t.enabled = true;

    if v_title is null then
      raise exception 'Tool is not available';
    end if;

    v_path := 'Teacher Tools';

  elsif p_event_type = 'tools_view' then
    v_title := 'Teacher Tools';
    v_path := 'Teacher Tools';

  -- Year page (the page showing Grades inside that Year).
  elsif p_event_type = 'year_view' then
    select y.name, y.id
      into v_title, v_year_id
    from public.school_years y
    where y.id = p_school_year_id;

    if v_title is null then
      raise exception 'Year not found';
    end if;

    v_path := v_title;

  -- Grade page (the page showing Units).
  elsif p_event_type = 'grade_view' then
    select
      g.name,
      g.id,
      y.id,
      concat_ws(' / ', y.name, g.name)
    into
      v_title,
      v_grade_id,
      v_year_id,
      v_path
    from public.grades g
    join public.school_years y on y.id = g.school_year_id
    where g.id = p_grade_id;

    if v_title is null then
      raise exception 'Grade not found';
    end if;

  -- Unit page (games/resources inside the Unit).
  elsif p_event_type = 'unit_view' then
    select
      coalesce(nullif(u.title, ''), u.name),
      u.id,
      g.id,
      y.id,
      concat_ws(' / ', y.name, g.name, u.name)
    into
      v_title,
      v_unit_id,
      v_grade_id,
      v_year_id,
      v_path
    from public.units u
    join public.grades g on g.id = u.grade_id
    join public.school_years y on y.id = g.school_year_id
    where u.id = p_unit_id
      and (public.is_admin() or public.has_unit_access(u.id));

    if v_title is null then
      raise exception 'Unit is not available';
    end if;

  elsif p_event_type = 'portal_home_view' then
    v_title := 'Learning Hub Home';
    v_path := 'Home';

  elsif p_event_type = 'community_view' then
    v_title := 'Community Forum';
    v_path := 'Community';

  elsif p_event_type = 'community_category_view' then
    v_title := coalesce(v_page_name, 'Community Category');
    v_path := concat_ws(' / ', 'Community', v_title);

  elsif p_event_type = 'forum_topic_view' then
    v_title := coalesce(v_page_name, 'Forum Topic');
    v_path := concat_ws(' / ', 'Community', v_title);
  end if;

  -- Prevent UI re-renders from creating duplicate page views.
  if p_event_type in (
    'portal_home_view','year_view','grade_view','unit_view','tools_view',
    'community_view','community_category_view','forum_topic_view'
  ) and exists (
    select 1
    from public.usage_events e
    where e.user_id = v_user_id
      and e.event_type = p_event_type
      and e.school_year_id is not distinct from v_year_id
      and e.grade_id is not distinct from v_grade_id
      and e.unit_id is not distinct from v_unit_id
      and e.content_title = v_title
      and e.created_at > now() - interval '10 seconds'
  ) then
    return;
  end if;

  -- Prevent a browser retry from counting the same game several times instantly.
  if p_event_type = 'game_play' and exists (
    select 1
    from public.usage_events e
    where e.user_id = v_user_id
      and e.event_type = 'game_play'
      and e.activity_id = v_activity_id
      and e.created_at > now() - interval '30 seconds'
  ) then
    return;
  end if;

  insert into public.usage_events (
    user_id,
    username,
    display_name,
    event_type,
    school_year_id,
    grade_id,
    unit_id,
    activity_id,
    resource_id,
    tool_id,
    content_title,
    path_text,
    page_name
  )
  values (
    v_user_id,
    v_username,
    v_display_name,
    p_event_type,
    v_year_id,
    v_grade_id,
    v_unit_id,
    v_activity_id,
    v_resource_id,
    v_tool_id,
    coalesce(v_title, 'Portal activity'),
    v_path,
    v_page_name
  );
end;
$$;

revoke all on function public.log_usage_event(
  text, uuid, uuid, uuid, uuid, uuid, uuid, text
) from public, anon;

grant execute on function public.log_usage_event(
  text, uuid, uuid, uuid, uuid, uuid, uuid, text
) to authenticated;

commit;

NOTIFY pgrst, 'reload schema';
