-- Pawn to Professor v1.9.8r
-- Public/login-page homepage analytics.
-- Stores NO IP address.
-- Uses a random browser UUID supplied by the browser.

begin;

create table if not exists public.public_home_visits (
  id bigint generated by default as identity primary key,
  visitor_key text not null,
  created_at timestamptz not null default now()
);

create index if not exists public_home_visits_created_at_idx
  on public.public_home_visits (created_at desc);

create index if not exists public_home_visits_visitor_key_created_at_idx
  on public.public_home_visits (visitor_key, created_at desc);

alter table public.public_home_visits enable row level security;

-- Nobody inserts directly from the browser.
revoke all on table public.public_home_visits from anon;
revoke all on table public.public_home_visits from authenticated;

-- Staff can read the analytics table.
grant select on table public.public_home_visits to authenticated;

drop policy if exists public_home_visits_staff_read on public.public_home_visits;
create policy public_home_visits_staff_read
on public.public_home_visits
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.id = auth.uid()
      and p.role in ('admin','owner')
      and p.status = 'active'
  )
);

-- Anonymous logging is only possible through this tightly-scoped function.
create or replace function public.log_public_home_visit(p_visitor_key text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_visitor_key is null
     or length(trim(p_visitor_key)) < 8
     or length(p_visitor_key) > 200 then
    return;
  end if;

  insert into public.public_home_visits(visitor_key)
  values (trim(p_visitor_key));
end;
$$;

revoke all on function public.log_public_home_visit(text) from public;
grant execute on function public.log_public_home_visit(text) to anon, authenticated;

commit;
